#
# Makefile for the LPM Provenance Monitor provenance system
#
# Authors: Devin J. Pohly <djpohly@cse.psu.edu>
#          Adam M. Bates <amb@cs.uoregon.edu>
#
# Copyright (C) 2013 MIT Lincoln Laboratory 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 2 of the License.
#

#obj-$(CONFIG_PROVENANCE_PROVMON) := provmon.o
obj-$(CONFIG_PROVENANCE_PROVMON) += provmon.o

